version: '3.8'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
      - "6379:6379"
      - "9092:9092"
      - "9000:9000"
      - "9001:9001"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petcaredb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: cisco1234
      MINIO_ENDPOINT: http://localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: petcare-bucket
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cisco1234
      MYSQL_DATABASE: petcaredb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
